### ISSUE TITLE
Error: Unexpected end of JSON input

### ISSUE THREAD

**Issue by tknuppe** [derhuerst/bvg-rest#13]
Hi

At the moment (for some weeks now) I'm getting errors when using the bvg-rest API docker image (latest tag, number 5). When I'm using the API from https://v5.bvg.transport.rest/ it works just fine. What's the difference between the docker image and the live API? I already updated to the latest tag (5) but it didn't help.

tl;dr
invalid json response body at https://bvg-apps-ext.hafas.de/bin/mgate.exe? reason: Unexpected end of JSON input

(Please note that my host port is 3500, this is intended and makes no difference because it is mapped to port 3000 anyway and it also doesn't work on host port 3000, just to be clear)

The Error output is as follows:

```
{"level":50,"time":1643227819745,"pid":1,"hostname":"BVG-REST","message":"invalid json response body at https://bvg-app
s-ext.hafas.de/bin/mgate.exe? reason: Unexpected end of JSON input","type":"invalid-json","stack":"FetchError: invalid 
json response body at https://bvg-apps-ext.hafas.de/bin/mgate.exe? reason: Unexpected end of JSON input\n    at /app/no
de_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n 
   at async collectionWithCache (/app/node_modules/cached-hafas-client/index.js:101:16)","msg":"invalid json response b
ody at https://bvg-apps-ext.hafas.de/bin/mgate.exe? reason: Unexpected end of JSON input"}                             
{"level":30,"time":1643227819751,"pid":1,"hostname":"BVG-REST","req":{"id":21,"method":"GET","url":"/stops/900000074201
/departures?results=3&duration=65&when=1643229013&direction=900000074202&remarks=false&bus=false&subway=false&tram=fals
e&ferry=false&express=false&regional=false","headers":{"host":"192.168.1.50:3500","user-agent":"GuzzleHttp/7"}},"res":{
"statusCode":500},"err":{"type":"Error","message":"failed with status code 500","stack":"Error: failed with status code
 500\n    at ServerResponse.onResFinished (/app/node_modules/pino-http/logger.js:77:38)\n    at ServerResponse.emit (no
de:events:402:35)\n    at onFinish (node:_http_outgoing:830:10)\n    at callback (node:internal/streams/writable:553:21
)\n    at afterWrite (node:internal/streams/writable:498:5)\n    at afterWriteTick (node:internal/streams/writable:485:
10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)"},"responseTime":402,"msg":"request err
ored"}
```

Greetings
Thomas

**Comment by derhuerst** [comment]
Glad you reported the issue!

This happens because [`hafas-client`, the underlying library that talks to BVG's HAFAS API,](https://github.com/public-transport/hafas-client) didn't get a valid JSON response from the server.

I *assume* that this is because their API has rate-limited your IP address or was down and therefore sends HTML or plain text. But I'm not sure.

Let's identify or rule out some possible causes:

- The error's stack trace indicates that you're running `bvg-rest` with `$REDIS_URL`, which means that it will use [`cached-hafas-client`](https://github.com/public-transport/cached-hafas-client) to cache responses of (successful) HAFAS requests. Can you either run with `DEBUG='cached-hafas-client*'`, or without the `$REDIS_URL` env var, so that I can see if `cached-hafas-client` is the culprit here?
- Which of `bvg-rest`'s paths are you calling? Provide a URL if possible, e.g. `http://localhost:3000/stops/900000191515/departures`.
- Did you try running the instance on a different (public) IP address, e.g. with a proxy or VPN if you're running it locally, or one a different server?

**Comment by derhuerst** [comment]
I have also updated the `derhuerst/bvg-rest:5`/`derhuerst/bvg-rest:latest` Docker images, so make sure to check if that solves the issue.

**Comment by tknuppe** [comment]
Hi Jannis
The updated docker image did the trick. It works again now!
Thank you for the quick response.

(I knew the Patreon support would be worth it some day ;D )

Good job!

regards
Thomas

**Comment by derhuerst** [comment]
Glad that made the problem disappear. Closing then.
