### ISSUE TITLE
Issue when calling deployed API

### ISSUE THREAD

**Issue by samstarling** [derhuerst/bvg-rest#2]
Firstly, thanks for this service/code – it's really useful. Sometimes, when hitting (for example) [this endpoint](https://1.bvg.transport.rest/trips/1|29906|0|86|3102018?lineName=U7), I get a 503 error with a body like this:

```
{"error":true,"msg":"no connection available"}
```

Is there something I'm doing wrong? It seems like a server-side issue, but I was curious if there's a way around this other than retrying.

**Comment by derhuerst** [comment]
[The BVG is frequently down for short periods of time.](https://status.transport.rest/780781263) This behaviour is really weird because (even though I've seen routes that crash the server, are not deterministic, etc.) I haven't seen the whole endpoint being down from time to time.

On the other hand, I haven't seen the BVG fail either. Maybe it's indeed related to how we ([`hafas-client`](
https://github.com/public-transport/hafas-client) specifically) query it, maybe not.

I will close this because my best guess is that we can't change the situation you described.
