### ISSUE TITLE
It returns me 502 every now and then?

### ISSUE THREAD

**Issue by AwaisKazi** [derhuerst/bvg-rest#5]
https://1.bvg.transport.rest/journeys returns 502 every now and then.

I only have a personal webpage, which I access only 5-10 times a week, so my IP should never be blocked too, and I can see that after a while it just seems to work fine.

**Comment by derhuerst** [comment]
`502` is the status code for "Bad Gateway". **The `1.bvg.transport.rest` endpoint returns it whenever the upstream BVG HAFAS API returns an error**; This could be because the latter a) is just down at the moment or b) blocks the former's IP address.

Our [`1.bvg.transport.rest` uptime monitor](https://status.transport.rest/781627008) shows how often this happens.

You can try running your own `bvg-rest` instance and see if it has better uptime, but my gut feeling says that it is indeed their HAFAS API being down. Please let me know about your experience!
